### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by kris-nova** [nivenly/genderidentity.io#12]
Initiate logo design and discussion here!

### Stories

As a user, I can easily tell what the site offers, and it makes me feel safe.
As a developer, I have many copies of the logo, in familiar, easy to use forms so I can use them in varies ways.

### Success Criteria 

- The logo is proposed, and accepted/agreed upon by the team
- The logo is offered in large formatting, and familiar encoding (PNG, JPEG, etc)
- The logo is stored in the repository with an Apache2 license

**Comment by ellenkorbes** [comment]
#17 applies here.

**Comment by renatap** [comment]
I started by selecting adjectives/values based on the [README.md](https://github.com/Nivenly/genderidentity.io/blob/master/README.md). These were: 

- accessible/open
- clean/neutral
- friendly
- informative

Here are two concepts I designed for genderidentity.io:
Please note they still need refining (especially the text), and the colours are just initial suggestions.

![genderidentity-05](https://user-images.githubusercontent.com/29361884/27342070-725508e6-55b5-11e7-84fb-ed513749deca.png)
![genderidentity-06](https://user-images.githubusercontent.com/29361884/27342078-77d0fd66-55b5-11e7-8e24-351e88f6f23e.png)
![genderidentity-07](https://user-images.githubusercontent.com/29361884/27342084-7cb94c48-55b5-11e7-8f13-b34baeb85939.png)

Everyone's welcome to comment with their suggestions, critique, to point subliminal messages I've missed, etc haha. Do you feel the logo successfully represents the values listed above? Is it welcoming enough? Does it make you feel safe? What do you think are the most adequate options?

**Comment by ellenkorbes** [comment]
I love the first concept, and I'm leaning towards the first icon alternative.

Curious to hear what everyone thinks too.

**Comment by swarnap** [comment]
I like the second concept.

**Comment by kris-nova** [comment]
+1 second concept from me
+1 second concept from my partner

**Comment by renatap** [comment]
Thank you for your feedback, I'll keep working!

**Comment by renatap** [comment]
Hi guys, I worked on more logo options and also refined the one you liked. I have to say it's very challenging to design a logo for something as abstract as "gender identity" that is both inclusive and representative. I wish there was a symbol that could represent that idea. Maybe in the future we can revisit this issue with a clearer picture of what the site represents. 

I thought a fingerprint would be a fun way to convey "identity", but the designs just looked too busy and didn't work in smaller sizes. For now, I chose to work with the initials and with a heart shape. I think that is simple and welcoming. I also used overlaping circles to represent our personal influences shaping our identities. In another option, I used a speech bubble to represent the community aspect of the site. The circles behind it are representing plurality of "voices".

These are the new concepts. If you have any comments, suggestions, or want to point out which elements you like best, that would be very helpful! 

![genderidentity_logov2](https://user-images.githubusercontent.com/29361884/27773030-5e4cef4a-5f46-11e7-9d49-c898f390873e.png)

**Comment by ellenkorbes** [comment]
I love concept 3 <3

**Comment by kris-nova** [comment]
Kris Vote: Concept 3
Kjersti Vote: Concept 3

**Comment by swarnap** [comment]
I thought I had voted for 3 as well...

**Comment by renatap** [comment]
Here are the colour options I pre-selected for the logo. I tested dozens of colour palettes, and decided blue would be a good color for our logo, since it evokes trust and is calming. That's important considering most of our readers will come to the website looking for answers and support, and we want to provide them trustworthy information and make them feel safe. However, blue alone would be dull and depressive in this case. I wanted to add more energy to the logo, to show this is a happy and thriving community, so I used orange-red for the main bubble (option 1). The bubbles behind it are in shades of blue.

I also made a version with the main bubble in blue and the other bubbles in green and orange. That logo gives the impression of being rainbow coloured.

The third option has the main bubble in blue, and the other bubble is coloured like the trans flag.

I think using the trans flag colors for the logo helps to link the identity of the website with transgender issues. However, using our own color palette would make the website's own identity stronger, and may be more inclusive of other gender identity issues.

As always, I would appreciate your opinion on this. Please, vote :)

![coloroptions](https://user-images.githubusercontent.com/29361884/28492241-dbdff670-6ed5-11e7-9fb1-231908f4fe3b.png)

Here they are in context: 

![logo_wireframe_1](https://user-images.githubusercontent.com/29361884/28492246-ea66801a-6ed5-11e7-9e7f-f9189a971a7e.png)
![logo_wireframe_2](https://user-images.githubusercontent.com/29361884/28492248-eac51b5c-6ed5-11e7-9d8e-1f69fab4d84e.png)
![logo_wireframe_3](https://user-images.githubusercontent.com/29361884/28492247-eab708be-6ed5-11e7-852c-d874e6bf6e1c.png)

**Comment by ellenkorbes** [comment]
It's so hard to choose one :|

I think my order of preference is the order they were presented in: option 1 > option 2 > option 3.

**Comment by ellenkorbes** [comment]
As per Slack comments, seems like #1 is the winner :)

**Comment by ellenkorbes** [comment]
Looks like we can close this one.
